services:
    kunstmaan_cache.menu_adaptor.varnish:
        class: Kunstmaan\CacheBundle\Helper\Menu\VarnishMenuAdaptor
        tags:
            -  { name: "kunstmaan_admin.menu.adaptor" }

    kunstmaan_cache.helper.varnish:
        class: Kunstmaan\CacheBundle\Helper\VarnishHelper
        arguments:
            - "@fos_http_cache.cache_manager"
            - "@kunstmaan_admin.domain_configuration"

    kunstmaan_cache.listener.varnish:
        class: Kunstmaan\CacheBundle\EventListener\VarnishListener
        arguments:
            - "@security.authorization_checker"
            - "@router"
        tags:
            - { name: 'kernel.event_listener', event: 'kunstmaan_node.configureActionMenu', method: 'onActionMenuConfigure' }

    Kunstmaan\CacheBundle\Controller\VarnishController:
        arguments: ['@kunstmaan_cache.helper.varnish']
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
