services:
    kunstmaan_lead_generation.popup.manager:
        class: Kunstmaan\LeadGenerationBundle\Service\PopupManager
        arguments: ['@doctrine.orm.entity_manager']

    kunstmaan_lead_generation.popup.twig.extension:
        class: Kunstmaan\LeadGenerationBundle\Twig\PopupTwigExtension
        arguments:
            - '@kunstmaan_lead_generation.popup.manager'
            - '@service_container'
            - '%kunstmaan_lead_generation.popup_types%'
            - '%kunstmaan_lead_generation.debug%'
        tags:
            - { name: twig.extension }

    kunstmaan_lead_generation.menu.adaptor:
        class: Kunstmaan\LeadGenerationBundle\Service\MenuAdaptor
        tags:
            - { name: kunstmaan_admin.menu.adaptor }

    kunstmaan_lead_generation.rule.form.localewhitelistrule:
        class: Kunstmaan\LeadGenerationBundle\Form\Rule\LocaleWhiteListAdminType
        arguments: ['@kunstmaan_admin.domain_configuration']
        tags:
            - { name: form.type }

    kunstmaan_lead_generation.rule.form.localeblacklistrule:
        class: Kunstmaan\LeadGenerationBundle\Form\Rule\LocaleBlackListAdminType
        arguments: ['@kunstmaan_admin.domain_configuration']
        tags:
            - { name: form.type }

    kunstmaan_lead_generation.rule.service.localeruleservice:
        class: Kunstmaan\LeadGenerationBundle\Service\Rule\LocaleRuleService
        arguments: ['@request_stack']

    Kunstmaan\LeadGenerationBundle\Controller\PopupsAdminListController:
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\LeadGenerationBundle\Controller\RulesAdminListController:
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
