kunstmaan_page_part:
    pagetemplates:
        legalpage:
            name: "Legal page"
            rows:
                - regions:
                    - { name: "legal_header", span: 12 }
                    - { name: "legal_main", span: 12 }
            template: "Pages\\LegalPage\\pagetemplate.html.twig"
