services:
    Kunstmaan\CookieBundle\EventSubscriber\CookieBarEventSubscriber:
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@twig'
            - '@kunstmaan_admin.adminroute.helper'
            - '@kunstmaan.legal_cookie_helper'

    Kunstmaan\CookieBundle\Helper\LegalCookieHelper:
        arguments: [ '@doctrine.orm.entity_manager', '%kunstmaan_admin.admin_firewall_name%' ]

    kunstmaan.legal_cookie_helper: '@Kunstmaan\CookieBundle\Helper\LegalCookieHelper'

    Kunstmaan\CookieBundle\Twig\CookieTwigExtension:
        arguments: [ '@doctrine.orm.entity_manager', '@kunstmaan.legal_cookie_helper', '@kunstmaan_admin.domain_configuration' ]
        tags:
            - { name: 'twig.extension' }

    Kunstmaan\CookieBundle\Helper\Menu\CookieMenuAdaptor:
        tags:
            - { name: 'kunstmaan_admin.menu.adaptor' }

    Kunstmaan\CookieBundle\Controller\LegalController:
        arguments: [ '@kunstmaan.legal_cookie_helper', '@doctrine.orm.entity_manager' ]
        calls:
            -   method: setContainer
                arguments: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\CookieBundle\Controller\CookieAdminListController:
        arguments: [ '@kunstmaan_admin.domain_configuration' ]
        calls:
            -   method: setContainer
                arguments: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\CookieBundle\Controller\CookieTypeAdminListController:
        calls:
            -   method: setContainer
                arguments: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\CookieBundle\Command\GenerateLegalCommand:
        arguments:
            - '@filesystem'
            - '@doctrine'
        tags:
            - { name: console.command }

    Kunstmaan\CookieBundle\ViewDataProvider\LegalPageViewDataProvider:
        arguments: [ '@request_stack', '@kunstmaan.legal_cookie_helper' ]
        tags: [ 'kunstmaan.node.page_view_data_provider' ]
