name: 'CI - Frontend'

on:
  [push, pull_request]

jobs:
    test:
        name: Validate frontend setup
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   uses: actions/setup-node@v3
                with:
                    node-version-file: '.nvmrc'
                    cache: 'yarn'

            -   name: Remove twig syntax from package.json
                run: |
                    sed -i -e 's/{% if demosite %}//g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
                    sed -i -e 's/{% endif %}//g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
                    sed -i -e 's/"name".*/"name":"demo",/g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json

            -   name: Install dependencies
                run: yarn

            -   run: |
                    npm run build -- --continueAfterTestError=true
# Temporary disable buildGroundControlSkeleton step as npm install takes a very long time.
#                    npm run buildGroundControlSkeleton
